name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
version-template: v0.1.0-beta$PATCH
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🔥 Hot Fixes'
    labels:
      - 'hotfix'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'maintain'
  - title: '👮 Security'
    label: 'security'
  - title: '🤖 Dependabot'
    label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
