nodeLinker: node-modules

progressBarStyle: hogsfather

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'current'
    - 'x64'
    - 'x86'
    - 'arm'
    - 'ia32'
  libc:
    - 'glibc'
    - 'musl'

yarnPath: .yarn/releases/yarn-4.1.0.cjs
