name: Previews
description: Github Action used to deploy preview environments, to Google Cloud Run.
author: "@joggrdocs"
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  #------------------
  # Deployment
  #------------------

  name:
    description: "The name of the service (must be unique) to be deployed."
    required: true
  port:
    description: "The port that the application will run on in the container."
    required: false
    default: "8080"
  env_vars:
    description: "List of environment variables that will be injected during runtime, each on a new line."
    required: false
  gcp_region:
    description: "The GCP Region where the service will be deployed."
    required: true
    default: "us-central1"
  gcp_project_id:
    description: "The GCP Project ID where the service will be deployed."
    required: true
  gcp_service_account_key:
    description: "The Service Account JSON Key used to push images to the GCP Artifact Registry."
    required: true
  gcp_artifact_repository:
    description: "The Artifact Registry name, you can override for custom names (i.e. the 'acme' in us-docker.pkg.dev/able-sailor-21423/acme)"
    required: true
  
  #------------------
  # Pull Request Integration
  #------------------

  github_token:
    description: "Github Token, pass in the `secrets.GITHUB_TOKEN`."
    required: true

  #------------------
  # Docker
  #------------------

  docker_file_name:
    description: "The Dockerfile name, you can override for custom names (i.e. DevDockerfile)"
    required: true
    default: "Dockerfile"
  docker_directory:
    description: "Directory where the DockerFile is located."
    required: true
    default: "."
  docker_build_args:
    description: "Comma separated list of arguments that will be injected during the build (i.e. FOO=bar,FOOBAR=foo)"
    required: false
outputs:
  url:
    description: "The preview URL for the running application"
    value: ${{ steps.deploy.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: '💬 Add Deployment in progress to Pull Request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          (async () => {
            try {
              const { number: prNumber, repository } = context.payload;
              
              const { data: pullRequest } = await github.rest.pulls.get({
                repo: repository.name,
                owner: repository.owner.login,
                pull_number: prNumber,
              });

              const body = `
          ${pullRequest.body.split('<!-- previews -->')[0].trim()}
          
          <!-- previews -->
          ---
          ### :warning: Deploying Preview :warning:
          Current deploying preview environment, check progress here: [GitHub Action for Previews](https://github.com/${repository.owner.login}/${repository.name}/actions/runs/${context.runId})
                `.trim();
              
              await github.rest.pulls.update({
                repo: repository.name,
                owner: repository.owner.login,
                pull_number: prNumber,
                body: body,
              });
            } catch (error) {
              core.setFailed(error);
            }
          })();

    - name: '#️⃣ Extract Pull Request #'
      uses: actions/github-script@v7
      id: pr-number
      with:
        result-encoding: string
        script: |
          if (!context.payload.number) {
            core.setFailed('No PR number found, you can only run Previews on Pull Requests.');
          }

          return context.payload;

    - name: '☁️ Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ inputs.gcp_project_id }}
        credentials_json: '${{ inputs.gcp_service_account_key }}'

    - name: '☁️ Setup Cloud SDK'
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ inputs.gcp_project_id }}
    
    - name: '🐳 Authorize Docker push'
      shell: bash
      run: gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: '🐳 Docker Build Arguments'
      uses: actions/github-script@v7
      id: docker-build-args
      env: 
        DOCKER_BUILD_ARGS: '${{ inputs.docker_build_args }}'
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const args = [];
          
          if (process.env.DOCKER_BUILD_ARGS) {
            const buildArgs = process.env.DOCKER_BUILD_ARGS.split(',');
            buildArgs.forEach((arg) => {
              const [key, value] = arg.split('=');
              args.push(`--build-arg ${key}=${value}`);
            });
          }

          return args.join(' ');

    - name: '🐳 Build and Push Container'
      shell: bash
      env: 
        BUILD_ARGS: '${{ steps.docker-build-args.outputs.result }}' 
      run: |-
        docker build \
          -t us-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.gcp_artifact_repository }}/${{ inputs.name }}:${{ github.sha }} \
          -f ${{ inputs.docker_directory }}/${{ inputs.docker_file_name }} \
          ${{ inputs.docker_directory }}
        docker push us-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.gcp_artifact_repository }}/${{ inputs.name }}:${{ github.sha }}

    - name: '🚀 Deploy to Cloud Run'
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ inputs.name }}-${{ github.sha }}
        image: us-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.gcp_artifact_repository }}/${{ inputs.name }}:${{ github.sha }}
        region: ${{ inputs.gcp_region }}
        suffix: pr${{ steps.pr-number.outputs.result }}-${{ github.sha }}
        env_vars: |
          PORT=${{ inputs.port }}
          ${{ inputs.env_vars }}

    - name: '💬 Add Deployment URL to Pull Request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          (async () => {
            try {
              const { number: prNumber, repository } = context.payload;
              
              const { data: pullRequest } = await github.rest.pulls.get({
                repo: repository.name,
                owner: repository.owner.login,
                pull_number: prNumber,
              });

              const body = `
          ${pullRequest.body.split('<!-- previews -->')[0].trim()}
          
          <!-- previews -->
          ---
          ### :rocket: Preview deployed
          View the preview here [Preview Environment](${steps.deploy.outputs.url}️)
                `.trim();
              
              await github.rest.pulls.update({
                repo: repository.name,
                owner: repository.owner.login,
                pull_number: prNumber,
                body: body,
              });
            } catch (error) {
              core.setFailed(error);
            }
          })();
    
    - name: '❌ Preview Failed'
      uses: actions/github-script@v7
      if: ${{ failure() }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          (async () => {
            try {
              const { number: prNumber, repository } = context.payload;
              
              const { data: pullRequest } = await github.rest.pulls.get({
                repo: repository.name,
                owner: repository.owner.login,
                pull_number: prNumber,
              });

              const body = `
          ${pullRequest.body.split('<!-- previews -->')[0].trim()}
          
          <!-- previews -->
          ---
          ### :x: Preview Failed
          View the issue here: [GitHub Action for Previews](https://github.com/${repository.owner.login}/${repository.name}/actions/runs/${context.runId})
                `.trim();
              
              await github.rest.pulls.update({
                repo: repository.name,
                owner: repository.owner.login,
                pull_number: prNumber,
                body: body,
              });
            } catch (error) {
              core.setFailed(error);
            }
          })(); 