name: "CI"

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  test_action:
    name: Test Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - id: runAction
        name: Run Action Code
        uses: ./
        with:
          name: previews-example
          port: 3000
          env_vars: |
            MESSAGE="Hello via ENV Vars"
          secrets: |
            SECRET_MESSAGE=secret_message:latest
          gcp_service_account_key: ${{ secrets.GCP_SA_KEY }}
          gcp_artifact_repository: joggr
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_directory: ./examples/nodejs-simple
          docker_file_name: DevDockerfile
          docker_build_args: |
            BUILD_VAR=foo
            BUILD_VAR2=bar
      - name: Test Outputs
        run: echo "${{ steps.runAction.outputs.url }}"
