name: "Security Scans"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  codescan:
    runs-on: ubuntu-latest
    name: Code Scannning
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
  audit-deps:
    runs-on: ubuntu-latest
    name: Audit Dependencies
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn
      - name: AuditJS OSSI
        run: npx auditjs@latest ossi .
